server.port=8080

# Supabase Credentials
supabase.url=https://ddelmbcqxuwminhjyemz.supabase.co
supabase.service.key=sb_secret_YE4kZ6HMoM1-4StPHx01CQ_cHciLeby
supabase.jwt.secret=iPTtSpV+YijuA1Nfna33KWfNu3WicsQIN+Z+SI2Ov9hjriW7PUfEqJGe/ftBOq9c7+ca7eCddPkzA4c8j5dCQA==

# Truecaller Credentials
truecaller.client.id=${TRUECALLER_CLIENT_ID:p1neytsiar1dvxogkaahekmp5uv4svgiomyxfooumjc}
truecaller.client.secret=${TRUECALLER_CLIENT_SECRET:}

# Twilio Credentials
twilio.account.sid=AC0a1444c3512ea5574caa62cdbe7bef0b
twilio.auth.token=fbde62cc9362eb8137f9f6fb7cc76650
twilio.phone.number=+17372508034

# Logging
logging.level.org.springframework.security=DEBUG
